{{- if .Values.platformApi.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.platformApi.serviceAccount.name }}
  namespace: {{ .Values.platformApi.namespace }}
  {{- with .Values.platformApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
