---
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: {{ .Values.platformApi.app.name }}
  namespace: {{ .Values.platformApi.namespace }}
spec:
  serviceRef:
    name: {{ .Values.platformApi.app.name }}
    port: {{ .Values.platformApi.service.ports.http }}
  targetGroupARN: {{ .Values.platformApi.targetGroup.arn }}
  targetType: {{ .Values.platformApi.targetGroup.targetType }}
