version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - echo "Building platform image..."
      - chmod +x ./scripts/build-platform-image.sh
      - ./scripts/build-platform-image.sh

artifacts:
  files:
    - '**/*'
