{{- if .Values.hyperfleetAdapter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperfleet-adapter.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.hyperfleetAdapter.broker.external.enabled .Values.hyperfleetAdapter.aws.podIdentity.enabled .Values.hyperfleetAdapter.aws.podIdentity.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.hyperfleetAdapter.aws.podIdentity.roleArn | quote }}
    {{- end }}
    {{- with .Values.hyperfleetAdapter.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
