{{- if .Values.hyperfleetAdapter.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hyperfleet-adapter.fullname" . }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
rules:
{{- range .Values.hyperfleetAdapter.rbac.resources }}
- apiGroups: [""]
  resources:
  - {{ . }}
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hyperfleet-adapter.fullname" . }}
  labels:
    {{- include "hyperfleet-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hyperfleet-adapter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hyperfleet-adapter.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
