{{- if .Values.hyperfleetApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperfleet-api.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-api.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.hyperfleetApi.database.external.enabled .Values.hyperfleetApi.aws.podIdentity.enabled .Values.hyperfleetApi.aws.podIdentity.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.hyperfleetApi.aws.podIdentity.roleArn | quote }}
    {{- end }}
    {{- with .Values.hyperfleetApi.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
