apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperfleet-api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hyperfleet-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hyperfleetApi.service.type }}
  ports:
  - port: {{ .Values.hyperfleetApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.hyperfleetApi.service.healthPort }}
    targetPort: health
    protocol: TCP
    name: health
  - port: {{ .Values.hyperfleetApi.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "hyperfleet-api.selectorLabels" . | nindent 4 }}
