{{- if and (eq .Values.hyperfleetSentinel.broker.type "rabbitmq") (not .Values.hyperfleetSentinel.broker.external.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  # RabbitMQ connection URL format: amqp://user:password@host:port/vhost
  BROKER_RABBITMQ_URL: {{ .Values.hyperfleetSentinel.broker.rabbitmq.url | quote }}
{{- end }}
