apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hyperfleetSentinel.service.type }}
  ports:
  - port: {{ .Values.hyperfleetSentinel.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "sentinel.selectorLabels" . | nindent 4 }}
