{{- if .Values.hyperfleetSentinel.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.hyperfleetSentinel.broker.external.enabled .Values.hyperfleetSentinel.aws.podIdentity.enabled .Values.hyperfleetSentinel.aws.podIdentity.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.hyperfleetSentinel.aws.podIdentity.roleArn | quote }}
    {{- end }}
    {{- with .Values.hyperfleetSentinel.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
