apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "maestro-agent.fullname" . }}-extension-apiserver
  namespace: kube-system
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["extension-apiserver-authentication"]
    verbs: ["get", "list", "watch"]
