apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maestro-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
automountServiceAccountToken: true
