apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.maestroServer.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "maestro-server.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "maestro-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "maestro-server.serviceAccountName" . }}
      {{- if gt (int .Values.maestroServer.deployment.zoneCount) 0 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "maestro-server.selectorLabels" . | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "maestro-server.selectorLabels" . | nindent 14 }}
      {{- end }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "maestro-server.fullname" . }}-secrets
      initContainers:
        - name: migration
          image: "{{ .Values.maestroServer.image.registry }}/{{ .Values.maestroServer.image.repository }}:{{ .Values.maestroServer.image.tag }}"
          imagePullPolicy: {{ .Values.maestroServer.image.pullPolicy }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          command:
            - /usr/local/bin/maestro
            - migration
            - --db-host-file=/mnt/secrets-store/db.host
            - --db-port-file=/mnt/secrets-store/db.port
            - --db-user-file=/mnt/secrets-store/db.user
            - --db-password-file=/mnt/secrets-store/db.password
            - --db-name-file=/mnt/secrets-store/db.name
            - --db-rootcert=
            - --db-sslmode={{ .Values.maestroServer.database.sslMode }}
            - --alsologtostderr
            - -v={{ .Values.maestroServer.maestro.glog_v }}
            {{- if .Values.maestroServer.database.usePasswordAuth }}
            - --db-auth-method=password
            {{- end }}
      containers:
        - name: service
          image: "{{ .Values.maestroServer.image.registry }}/{{ .Values.maestroServer.image.repository }}:{{ .Values.maestroServer.image.tag }}"
          imagePullPolicy: {{ .Values.maestroServer.image.pullPolicy }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          env:
            {{- if .Values.maestroServer.tracing.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.maestroServer.tracing.address | quote }}
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.maestroServer.tracing.exporter | quote }}
            {{- end }}
            - name: AMS_ENV
              value: "production"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - /usr/local/bin/maestro
            - server
            - --db-host-file=/mnt/secrets-store/db.host
            - --db-port-file=/mnt/secrets-store/db.port
            - --db-user-file=/mnt/secrets-store/db.user
            - --db-password-file=/mnt/secrets-store/db.password
            - --db-name-file=/mnt/secrets-store/db.name
            - --db-rootcert=
            - --db-sslmode={{ .Values.maestroServer.database.sslMode }}
            - --db-max-open-connections={{ .Values.maestroServer.database.maxOpenConnections }}
            - --message-broker-config-file=/mnt/secrets-store/config.yaml
            - --message-broker-type={{ .Values.maestroServer.broker.type }}
            - --enable-https=false
            - --enable-grpc-server=true
            - --disable-grpc-tls=true
            - --server-hostname=
            - --http-server-bindport={{ .Values.maestroServer.maestro.httpBindPort }}
            - --grpc-server-bindport={{ .Values.maestroServer.maestro.grpcBindPort }}
            - --metrics-server-bindport=9090
            - --health-check-server-bindport={{ .Values.maestroServer.maestro.healthCheckBindPort }}
            - --enable-health-check-https=false
            - --enable-db-debug={{ .Values.maestroServer.database.debug }}
            - --enable-metrics-https=false
            - --http-read-timeout={{ .Values.maestroServer.maestro.httpReadTimeout }}s
            - --http-write-timeout={{ .Values.maestroServer.maestro.httpWriteTimeout }}s
            - --label-metrics-inclusion-duration={{ .Values.maestroServer.maestro.labelMetricsInclusionDuration }}
            - --alsologtostderr
            - -v={{ .Values.maestroServer.maestro.glog_v }}
            {{- if .Values.maestroServer.database.usePasswordAuth }}
            - --db-auth-method=password
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.maestroServer.deployment.requests.cpu | quote }}
              memory: {{ .Values.maestroServer.deployment.requests.memory | quote }}
            limits:
              cpu: {{ .Values.maestroServer.deployment.limits.cpu | quote }}
              memory: {{ .Values.maestroServer.deployment.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.maestroServer.maestro.healthCheckBindPort }}
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.maestroServer.maestro.healthCheckBindPort }}
              scheme: HTTP
              httpHeaders:
                - name: User-Agent
                  value: Probe
            initialDelaySeconds: 20
            periodSeconds: 5
