apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maestro-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-server.labels" . | nindent 4 }}
  {{- if .Values.maestroServer.aws.podIdentity.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.maestroServer.aws.podIdentity.roleArn | quote }}
  {{- end }}
automountServiceAccountToken: true
